services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET
      - DATABASE_URL
      - BACKEND_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    networks:
      - app
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ongeki
    volumes:
      - only-geeks-db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  only-geeks-db:
