export const BASE_PATH = '/'

export const PROFILE_PATH = BASE_PATH + 'profile'
export const USER_PROFILE_PATH = BASE_PATH + 'user/' + ':username'
export const SETTINGS_PATH = BASE_PATH + 'settings'
export const SEARCH_PATH = BASE_PATH + 'search/:query'
export const CREATE_BLOG_PATH = BASE_PATH + 'create/blog'
export const CREATE_PROJECT_PATH = BASE_PATH + 'create/project'
export const CREATE_EDUCATION_PATH = BASE_PATH + 'create/education'
export const CREATE_ACHIEVEMENT_PATH = BASE_PATH + 'create/achievement'
export const BLOG_READER_PATH = BASE_PATH + 'blog/' + ':username' + '/:slug'
